### ISSUE TITLE
Port to 1.8

### ISSUE THREAD

**Issue by gr8pefish** [sapient/iBench#5]
Hey, just wondering if you care if I fork and port to 1.8?

I won't be able to do it _for a while_ (if I even do it at all), but I just wanted to ask anyway. I figure porting a small mod to 1.8 will help me learn how 1.8 works, so I have that knowledge for the future (i.e. 1.9+).

Would you care if I did my own thing with it as well? Maybe changed the name and some recipes? It would stay a small mod of just a portable crafting table. While the license doesn't explicitly state anything, I know how it feels to have something be your own work so I want to respect your wishes and if you want to keep it "yours" I understand.

Cheers,
gr8pefish

**Comment by sapient** [comment]
Hey man, been a while. 

It uses the MIT license, so you are free to do absolutely anything you like with it except change the license on your version, or any version based on iBench to anything other than the MIT license. Strangely, I also started playing MC again last weekend, and thought about porting to 1.8, I guess we will see who does it first, though I don't don't even have a JDK installed at the moment ;)

Anyway, knock yourself out man, and good luck!

ps. If you do port it, there is a crash when you die while having the UI open and OpenBlocks gravestones enabled that I couldn't figure out, though it may be fixed with a newer version of OB.

Cheers
Sapient

**Comment by gr8pefish** [comment]
Hey, yeah it has been ages :)

Strange coincidence that we both started again at the same time. I am quite [busy](https://github.com/gr8pefish/IronBackpacks/graphs/contributors) with Iron Backpacks, so you will probably beat me to it, but if you don't then I will give the port a shot. You obviously get first dibs though.

**Comment by gr8pefish** [comment]
Hey!

So I ported it to 1.8.9 :D

I changed the name and made it a little simpler (only the basic version of the portable crafter exists). I still have to add JEI integration and do some cleanup. It's still under MIT license, of course.

[Here](https://github.com/gr8pefish/PortableCrafting) is the repo.

Cheers!

**Comment by gr8pefish** [comment]
I finished the port, just waiting on curse to approve the project. [Here](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2595495-portable-crafting) is the MCF post about it. Just figured I'd give you a heads up.

If you want to port your mod over exactly as it is (i.e. without my changes), feel free to look at my repo for guidance!
